version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alten-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
    networks:
      - alten-network
    restart: unless-stopped

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alten-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - alten-network
    restart: unless-stopped

networks:
  alten-network:
    driver: bridge

volumes:
  backend-data:
